.\" $Header$
.TH 8080_AS 6 "$Revision$"
.ad
.SH NAME
8080_as \- assembler for Intel 8080 and 8085
.SH SYNOPSIS
~em/lib.bin/8080/as [options] argument ...
.SH DESCRIPTION
This assembler is made with the general framework
described in \fIuni_ass\fP(6). It is an assembler generating relocatable
object code in \fIack.out\fP(5) format.
.SH SYNTAX
.IP registers
The 8080 has seven one-byte registers: a, b, c, d, e, h, l;
and two two-byte registers: sp and psw, respectively the stack pointer
and the processor status word.
.IP "addressing modes"
.nf
.ta 8n 16n 24n 32n 40n 48n
syntax		meaning

expr		one- or two-byte address or immediate
		data, depending on the instruction.

a,b,c,d,e,h,l
sp,psw		(lower byte) of register

b,d,h		register-pair b-c, d-e, or h-l

m		register-pair h-l is address of
		(one or two byte) operand
.fi
.SH "SEE ALSO"
uni_ass(1),
ack(1),
ack.out(5),
.br
System 80/20-4 microcomputer hardware reference manual, 1978 Intel corporation
