.\" $Header$
.TH ARM_AS 1
.ad
.SH NAME
arm_as \- assembler for ARM

.SH SYNOPSIS
/usr/em/lib/arm_as [options] argument ...

.SH DESCRIPTION
This assembler is made with the general framework
described in \fIuni_ass\fP(6).

.SH SYNTAX
This assembler is very old and doesn't use standard opcode mnemonics. Use at
your own risk.

.SH "SEE ALSO"
uni_ass(6),
ack(1),
.SH EXAMPLE
.nf
.ta 8n 16n 24n 32n 40n 48n
Todo.
.fi
