/*
 * (c) copyright 1987 by the Vrije Universiteit, Amsterdam, The Netherlands.
 * See the copyright notice in the ACK home directory, in the file "Copyright".
 */
#define RCSID3 "$Id$"

/*
 * Zilog Z80 keywords
 */

{0,     R8,             B,              "b"},
{0,     R8,             C,              "c"},
{0,     R8,             D,              "d"},
{0,     R8,             E,              "e"},
{0,     R8,             H,              "h"},
{0,     R8,             L,              "l"},
{0,     R8,             F,              "f"},
{0,     R8,             A,              "a"},
{0,     R8,             I,              "i"},
{0,     R8,             R,              "r"},
{0,     R24,            BC,             "bc"},
{0,     R24,            DE,             "de"},
{0,     R24,            HL,             "hl"},
{0,     R24,            SP,             "sp"},
{0,     R24,            AF,             "af"},
{0,     R24,            AF2,            "af2"},
{0,     R24,            IX,             "ix"},
{0,     R24,            IY,             "iy"},
{0,     CC,             0,              "nz"},
{0,     CC,             1,              "z"},
{0,     CC,             2,              "nc"},
{0,     CC,             4,              "po"},
{0,     CC,             5,              "pe"},
{0,     CC,             6,              "p"},
{0,     CC,             7,              "m"},
{0,     LDOP,           0,              "ld"},
{0,     PSHPOP,         0305,           "push"},
{0,     PSHPOP,         0301,           "pop"},
{0,     EXOP,           0343,           "ex"},
{0,     NOOPOP,         0331,           "exx"},
{0,     E_ED,           0240,           "ldi"},
{0,     E_ED,           0260,           "ldir"},
{0,     E_ED,           0250,           "ldd"},
{0,     E_ED,           0270,           "lddr"},
{0,     E_ED,           0241,           "cpi"},
{0,     E_ED,           0261,           "cpir"},
{0,     E_ED,           0251,           "cpd"},
{0,     E_ED,           0271,           "cpdr"},
{0,     ADDOP,          0200,           "add"},
{0,     ADCSBC,         0210,           "adc"},
{0,     ADCSBC,         0230,           "sbc"},
{0,     ARI8,           0220,           "sub"},
{0,     ARI8,           0240,           "and"},
{0,     ARI8,           0260,           "or"},
{0,     ARI8,           0250,           "xor"},
{0,     ARI8,           0270,           "cp"},
{0,     INCDEC,         04,             "inc"},
{0,     INCDEC,         05,             "dec"},
{0,     NOOPOP,         047,            "daa"},
{0,     NOOPOP,         057,            "cpl"},
{0,     E_ED,           0104,           "neg"},
{0,     NOOPOP,         077,            "ccf"},
{0,     NOOPOP,         067,            "scf"},
{0,     NOOPOP,         0,              "nop"},
{0,     NOOPOP,         0166,           "halt"},
{0,     NOOPOP,         0363,           "di"},
{0,     NOOPOP,         0373,           "ei"},
{0,     IMOP,           0106,           "im"},
{0,     NOOPOP,         07,             "rlca"},
{0,     NOOPOP,         027,            "rla"},
{0,     NOOPOP,         017,            "rrca"},
{0,     NOOPOP,         037,            "rra"},
{0,     ROTATE,         0,              "rlc"},
{0,     ROTATE,         020,            "rl"},
{0,     ROTATE,         010,            "rrc"},
{0,     ROTATE,         030,            "rr"},
{0,     ROTATE,         040,            "sla"},
{0,     ROTATE,         050,            "sra"},
{0,     ROTATE,         070,            "srl"},
{0,     E_ED,           0157,           "rld"},
{0,     E_ED,           0147,           "rrd"},
{0,     BITS,           0100,           "bit"},
{0,     BITS,           0200,           "res"},
{0,     BITS,           0300,           "set"},
{0,     JP,             0303,           "jp"},
{0,     JR,             030,            "jr"},
{0,     DJNZ,           020,            "djnz"},
{0,     CALL,           0315,           "call"},
{0,     RET,            0311,           "ret"},
{0,     E_ED,           0115,           "reti"},
{0,     E_ED,           0105,           "retn"},
{0,     RST,            0307,           "rst"},
{0,     IN,             0333,           "in"},
{0,     E_ED,           0242,           "ini"},
{0,     E_ED,           0262,           "inir"},
{0,     E_ED,           0252,           "ind"},
{0,     E_ED,           0272,           "indr"},
{0,     OUT,            0323,           "out"},
{0,     E_ED,           0243,           "outi"},
{0,     E_ED,           0263,           "otir"},
{0,     E_ED,           0253,           "outd"},
{0,     E_ED,           0273,           "otdr"},
{0,     PEA,            0,              "pea"},
{0,     LEA,            0,              "lea"},

// vim: ts=4 sw=4 et

