.TH PC_PEM 6ACK
.ad
.SH NAME
pc_pem \- Pascal to EM compiler
.SH SYNOPSIS
~em/lib/pc_pem compact errors
.SH DESCRIPTION
Pem is a Pascal compiler producing compact EM assembly code.
The EM machine is described in [1].
The language Pascal is developed by N. Wirth and is described
in the "Pascal User Manual and Report" [2].
The compiler complies as much as possible with the ISO standard proposal [3].
The language features as processed by this compiler are described in
the Pascal reference manual [4].
Normally the compiler is called by means of the user interface program
\fIack\fP(I).
.PP
The first argument is the name of the file on which the produced
compact EM code is written.
The file is also used to pass the options to the compiler.
These options include the -{xxx} flags given to \fIack\fP(I)
and the size of Pascal objects, like pointers.
.PP
The second argument is the name of the error file.
For each error found by the compiler a record is appended to this file.
An error record contains several fields like error number, line number,
column number and error parameter (identifier name or label number etc.).
.SH "SEE ALSO"
.IP [1]
A.S. Tanenbaum, Hans van Staveren, Ed Keizer and Johan
Stevenson "Description of a machine architecture for use with
block structured languages" Informatica report IR-81.
.IP [2]
K.Jensen & N.Wirth
"PASCAL, User Manual and Report" Springer-Verlag.
.IP [3]
An improved version of the ISO standard proposal for the language Pascal,
ISO/TC97/SC5-N462, received November 1979.
.IP [4]
J.W.Stevenson "The Amsterdam Compiler Kit Pascal reference manual".
.br
(try \fInroff ~em/doc/pcref.doc\fP)
.IP [5]
\fIack\fP(I)
.SH DIAGNOSTICS
Compilation errors are written to the error file.
Positive error numbers are used for irrecoverable errors, negative ones for warnings.
\fIAck\fP searches the file ~em/etc/pc_errors to find
the corresponding messages.
.SH AUTHOR
Johan Stevenson, Vrije Universiteit.
