clibrary {
	name = "lib",
	srcs = {
		"./access.c",
		"./aprintf.c",
		"./basename.c",
		"./break.c",
		"./chmode.c",
		"./close.c",
		"./create.c",
		"./filesize.c",
		"./maketempfile.c",
		"./modtime.c",
		"./open.c",
		"./read.c",
		"./remove.c",
		"./rename.c",
		"./seek.c",
		"./setbinarymode.c",
		"./stop.c",
		"./strndup.c",
		"./syssystem.c",
		"./system.c",
		"./tmpdir.c",
		"./write.c",
		--"./lock.c",
		--"./unlock.c”,
	},
	hdrs = { "./system.h" },
}
