.\" $Header$
.TH ARCH 1 "$Revision$"
.ad
.SH NAME
arch \- archive and library maintainer
.SH SYNOPSIS
.B arch
key afile name ...
.SH DESCRIPTION
.I Arch
maintains groups of files
combined into a single archive file.
The Amsterdam compiler kit provides its own archiver with a
fixed, machine-independent format, much like the UNIX-V7
archive format.
.PP
.I Key
is one character from the set
.B adrtpx,
optionally concatenated with
one or more of
.B vlc.
.I Afile
is the archive file.
The
.I names
are constituent files in the archive file.
The meanings of the
.I key
characters are:
.TP
.B d
Delete the named files from the archive file.
.TP
.B a
Append the named files to the archive file.
.TP
.B r
Replace the named files in the archive file.
New files are placed at the end.
.TP
.B t
Print a table of contents of the archive file.
If no names are given, all files in the archive are listed.
If names are given, only those files are listed.
.TP
.B p
Print the named files in the archive.
.TP
.B x
Extract the named files.
If no names are given, all files in the archive are
extracted.
In neither case does
.B x
alter the archive file.
.TP
.B v
Verbose.
Under the verbose option,
.I arch
gives a file-by-file
description of the making of a
new archive file from the old archive and the constituent files.
When used with
.B t,
it gives a long listing of all information about the files.
When used with
.BR p ,
it precedes each file with a name.
.TP
.B l
Local.
Normally
.I arch
places its temporary files in the directory /tmp.
This option causes them to be placed in the local directory.
.TP
.B c
Create. Normally
.I arch
will create
.I afile
when it needs to.
The create option supresses the normal message that is produced when
.I afile
is created.
.SH FILES
/tmp/ar.* temporaries
.SH "SEE ALSO"
em_ass(1), arch(5),
.SH BUGS
If the same file is mentioned twice in an argument list,
it may be put in the archive twice.
