.TH ANM 1 "$Revision$"
.SH NAME
anm  \-  print name list
.SH SYNOPSIS
anm [ \-gnoprus ] [ file ... ]
.SH DESCRIPTION
.I Anm
prints the name list (symbol table) of each ack.out(5) format object
.I file
in the argument list. If an argument is an aal(1) or arch(1) archive,
a listing of each object file in the archive will be produced.
If no
.I file
is given, the symbols in
`a.out'
are listed.
.PP
Each symbol name is preceded by its value, a section indicator
and a type indicator.
A section indicator can be
.SM
.B U
(undefined symbol),
.SM
.B A
(absolute symbol),
.SM
.B C
(common symbol), a section number (section related symbol),
or
.SM
.B -
(other symbol).
A type indicator can be
.SM
.B F
(filename),
.SM
.B M
(module name),
.SM
.B E
(external (global) symbol),
or
.SM
.B -
(local symbol).
The output is sorted alphabetically.
.PP
Options are:
.TP
.B  \-g
Print only external (global) symbols.
.TP
.B \-n
Sort numerically rather than alphabetically.
.TP
.B  \-o
Prepend file name to each output line rather than only once.
.TP
.B  \-p
Don't sort; print in symbol-table order.
.TP
.B  \-r
Sort in reverse order.
.TP
.B  \-u
Print only undefined symbols.
.TP
.B  \-s
Sort in section order.
.sh FILES
.SH SEE ALSO
ack.out(5)
