.TH ASHOW 1 2017-01-18
.SH NAME
ashow \- make the contents of an ACK object file human readable
.SH SYNOPSIS
ashow inputfile inputfile...
.SH DESCRIPTION
.I ashow
dumps the contents of an ack.out file in human-readable form.
It shows
details of all symbols, relocation entries, sections, and other information.
.SH "SEE ALSO"
ack.out(5)
