.TH ASIZE 1 "$Revision$"
.SH NAME
asize \- size of an object file
.SH SYNOPSIS
asize [ file ... ]
.SH DESCRIPTION
.I Asize
prints the (decimal) number of bytes
required by the different sections,
and their sum in decimal and hexadecimal,
of each ack.out(5) format object file argument.
If no file is specified,
`a.out'
is used.
.SH "SEE ALSO"
ack.out(5)
