.TH ASTRIP 1 2017-01-18
.SH NAME
astrip  \-  remove symbols and relocation information
.SH SYNOPSIS
astrip file ...
.SH DESCRIPTION
.I Astrip
removes the symbol
table and relocation information ordinarily attached to the
ack.out(5) format object files.
This is useful to save space after a program has been
debugged.
.SH FILES
.IP /tmp/s? 16n
temporary file
.SH "SEE ALSO"
ack.out(5)
