for _, plat in ipairs(vars.plats) do
	acklibrary {
		name = "lib_"..plat,
		srcs = {
			"./aar2.s",
			"./aar.s",
			"./aaru.s",
			"./and.s",
			"./cii.s",
			"./cms.s",
			"./cmu4.s",
			"./cmu.s",
			"./csa.s",
			"./csb.s",
			"./dvi2.s",
			"./dvi4.s",
			"./dvu2.s",
			"./dvu4.s",
			"./exg.s",
			"./gto.s",
			"./hulp.s",
			"./inn.s",
			"./ior.s",
			"./lar2.s",
			"./lar.s",
			"./laru.s",
			"./los.s",
			"./mli2.s",
			"./mli4.s",
			"./nop.s",
			"./outdec.s",
			"./rck.s",
			"./ret.s",
			"./rmi2.s",
			"./sar2.s",
			"./sar.s",
			"./saru.s",
			"./sdf.s",
			"./sdl.s",
			"./set.s",
			"./str.s",
			"./sts.s",
			"./trp.s",
			"./unim.s",
			"./xor.s",
		},
		vars = {
			plat = plat,
			["+ackcflags"] = {"-Imach/z80/libem"}
		},
	}
end

