/** @file
 *  For disassembling the text segment.
 */

/* $Id$ */

#include "global.h"
#include "opcode.h"
#include "memdirect.h"
#include "proctab.h"
#include "alloc.h"
#include "whatever.h"

static ptr TC;
static void do_pr_instr(unsigned int);

/* This text is copied and modified from text.h */

#define text_loc(a) (*(text + (p2i(a))))

/*	Reading the opcode.
 */
#define nextTCbyte() (TC += 1, btou(text_loc(TC - 1)))

/*	Shortie arguments consist of the high order value, derived from
 the opcode and passed as a parameter, and the following byte.
 */
#define St_arg(h) (TC += 1, ((h) << 8) + btol(text_loc(TC - 1)))

/*	Two-byte arguments consist of the following two bytes.
 */

#define Lt_arg_2() (TC += 2, (btol(text_loc(TC - 1)) | (btos(text_loc(TC - 2)) << 8)))

#define Pt_arg_2()                                                                                 \
	(TC += 2, (btol(text_loc(TC - 1)) | (btos(text_loc(TC - 2)) << 8))) /* should test */

#define Nt_arg_2()                                                                                 \
	(TC += 2, (btol(text_loc(TC - 1)) | (btos(text_loc(TC - 2)) << 8))) /* should test */

#define Ut_arg() (TC += 2, (btol(text_loc(TC - 1)) | (btol(text_loc(TC - 2)) << 8)))

/*	The L-, P-, and N-4-bytes #defines are all equal, because
 we assume our longs to be 4 bytes long.
 */

#define Lt_arg_4()                                                                                 \
	(TC += 4,                                                                                      \
	 (btol(text_loc(TC - 1)) | (btol(text_loc(TC - 2)) << 8) | (btol(text_loc(TC - 3)) << 16)      \
	  | (btos(text_loc(TC - 4)) << 24)))

#define Pt_arg_4()                                                                                 \
	(TC += 4,                                                                                      \
	 (btol(text_loc(TC - 1)) | (btol(text_loc(TC - 2)) << 8) | (btol(text_loc(TC - 3)) << 16)      \
	  | (btos(text_loc(TC - 4)) << 24))) /* should test */

#define Nt_arg_4()                                                                                 \
	(TC += 4,                                                                                      \
	 (btol(text_loc(TC - 1)) | (btol(text_loc(TC - 2)) << 8) | (btol(text_loc(TC - 3)) << 16)      \
	  | (btos(text_loc(TC - 4)) << 24))) /* should test */

/* This text was generated by mkswitch Pr and then modified */

static void PrAARl2(long arg)
{
	printf(" AAR %ld\n", Lt_arg_2() * arg);
}

static void PrAARm(long arg)
{
	printf(" AAR %ld\n", arg);
}

static void PrAARz(void)
{
	printf(" AAR\n");
}

static void PrADFl2(long arg)
{
	printf(" ADF %ld\n", Lt_arg_2() * arg);
}

static void PrADFs(long hob, size wfac)
{
	printf(" ADF %ld\n", St_arg(hob) * wfac);
}

static void PrADFz(void)
{
	printf(" ADF\n");
}

static void PrADIl2(long arg)
{
	printf(" ADI %ld\n", Lt_arg_2() * arg);
}

static void PrADIm(long arg)
{
	printf(" ADI %ld\n", arg);
}

static void PrADIz(void)
{
	printf(" ADI\n");
}

static void PrADPl2(long arg)
{
	printf(" ADP %ld\n", Lt_arg_2() * arg);
}

static void PrADPl4(long arg)
{
	printf(" ADP %ld\n", Lt_arg_4() * arg);
}

static void PrADPm(long arg)
{
	printf(" ADP %ld\n", arg);
}

static void PrADPs(long hob, size wfac)
{
	printf(" ADP %ld\n", St_arg(hob) * wfac);
}

static void PrADSl2(long arg)
{
	printf(" ADS %ld\n", Lt_arg_2() * arg);
}

static void PrADSm(long arg)
{
	printf(" ADS %ld\n", arg);
}

static void PrADSz(void)
{
	printf(" ADS\n");
}

static void PrADUl2(long arg)
{
	printf(" ADU %ld\n", Lt_arg_2() * arg);
}

static void PrADUz(void)
{
	printf(" ADU\n");
}

static void PrANDl2(long arg)
{
	printf(" AND %ld\n", Lt_arg_2() * arg);
}

static void PrANDm(long arg)
{
	printf(" AND %ld\n", arg);
}

static void PrANDz(void)
{
	printf(" AND\n");
}

static void PrASPl2(long arg)
{
	printf(" ASP %ld\n", Lt_arg_2() * arg);
}

static void PrASPl4(long arg)
{
	printf(" ASP %ld\n", Lt_arg_4() * arg);
}

static void PrASPm(long arg)
{
	printf(" ASP %ld\n", arg);
}

static void PrASPs(long hob, size wfac)
{
	printf(" ASP %ld\n", St_arg(hob) * wfac);
}

static void PrASSl2(long arg)
{
	printf(" ASS %ld\n", Lt_arg_2() * arg);
}

static void PrASSz(void)
{
	printf(" ASS\n");
}

static void PrBEQl2(long arg)
{
	printf(" BEQ %ld\n", Lt_arg_2() * arg);
}

static void PrBEQl4(long arg)
{
	printf(" BEQ %ld\n", Lt_arg_4() * arg);
}

static void PrBEQs(long hob, size wfac)
{
	printf(" BEQ %ld\n", St_arg(hob) * wfac);
}

static void PrBGEl2(long arg)
{
	printf(" BGE %ld\n", Lt_arg_2() * arg);
}

static void PrBGEl4(long arg)
{
	printf(" BGE %ld\n", Lt_arg_4() * arg);
}

static void PrBGEs(long hob, size wfac)
{
	printf(" BGE %ld\n", St_arg(hob) * wfac);
}

static void PrBGTl2(long arg)
{
	printf(" BGT %ld\n", Lt_arg_2() * arg);
}

static void PrBGTl4(long arg)
{
	printf(" BGT %ld\n", Lt_arg_4() * arg);
}

static void PrBGTs(long hob, size wfac)
{
	printf(" BGT %ld\n", St_arg(hob) * wfac);
}

static void PrBLEl2(long arg)
{
	printf(" BLE %ld\n", Lt_arg_2() * arg);
}

static void PrBLEl4(long arg)
{
	printf(" BLE %ld\n", Lt_arg_4() * arg);
}

static void PrBLEs(long hob, size wfac)
{
	printf(" BLE %ld\n", St_arg(hob) * wfac);
}

static void PrBLMl2(long arg)
{
	printf(" BLM %ld\n", Lt_arg_2() * arg);
}

static void PrBLMl4(long arg)
{
	printf(" BLM %ld\n", Lt_arg_4() * arg);
}

static void PrBLMs(long hob, size wfac)
{
	printf(" BLM %ld\n", St_arg(hob) * wfac);
}

static void PrBLSl2(long arg)
{
	printf(" BLS %ld\n", Lt_arg_2() * arg);
}

static void PrBLSz(void)
{
	printf(" BLS\n");
}

static void PrBLTl2(long arg)
{
	printf(" BLT %ld\n", Lt_arg_2() * arg);
}

static void PrBLTl4(long arg)
{
	printf(" BLT %ld\n", Lt_arg_4() * arg);
}

static void PrBLTs(long hob, size wfac)
{
	printf(" BLT %ld\n", St_arg(hob) * wfac);
}

static void PrBNEl2(long arg)
{
	printf(" BNE %ld\n", Lt_arg_2() * arg);
}

static void PrBNEl4(long arg)
{
	printf(" BNE %ld\n", Lt_arg_4() * arg);
}

static void PrBNEs(long hob, size wfac)
{
	printf(" BNE %ld\n", St_arg(hob) * wfac);
}

static void PrBRAl2(long arg)
{
	printf(" BRA %ld\n", Lt_arg_2() * arg);
}

static void PrBRAl4(long arg)
{
	printf(" BRA %ld\n", Lt_arg_4() * arg);
}

static void PrBRAs(long hob, size wfac)
{
	printf(" BRA %ld\n", St_arg(hob) * wfac);
}

static void PrCAIz(void)
{
	printf(" CAI\n");
}

static void PrCALl2(long arg)
{
	printf(" CAL %ld\n", Lt_arg_2() * arg);
}

static void PrCALl4(long arg)
{
	printf(" CAL %ld\n", Lt_arg_4() * arg);
}

static void PrCALm(long arg)
{
	printf(" CAL %ld\n", arg);
}

static void PrCALs(long hob, size wfac)
{
	printf(" CAL %ld\n", St_arg(hob) * wfac);
}

static void PrCFFz(void)
{
	printf(" CFF\n");
}

static void PrCFIz(void)
{
	printf(" CFI\n");
}

static void PrCFUz(void)
{
	printf(" CFU\n");
}

static void PrCIFz(void)
{
	printf(" CIF\n");
}

static void PrCIIz(void)
{
	printf(" CII\n");
}

static void PrCIUz(void)
{
	printf(" CIU\n");
}

static void PrCMFl2(long arg)
{
	printf(" CMF %ld\n", Lt_arg_2() * arg);
}

static void PrCMFs(long hob, size wfac)
{
	printf(" CMF %ld\n", St_arg(hob) * wfac);
}

static void PrCMFz(void)
{
	printf(" CMF\n");
}

static void PrCMIl2(long arg)
{
	printf(" CMI %ld\n", Lt_arg_2() * arg);
}

static void PrCMIm(long arg)
{
	printf(" CMI %ld\n", arg);
}

static void PrCMIz(void)
{
	printf(" CMI\n");
}

static void PrCMPz(void)
{
	printf(" CMP\n");
}

static void PrCMSl2(long arg)
{
	printf(" CMS %ld\n", Lt_arg_2() * arg);
}

static void PrCMSs(long hob, size wfac)
{
	printf(" CMS %ld\n", St_arg(hob) * wfac);
}

static void PrCMSz(void)
{
	printf(" CMS\n");
}

static void PrCMUl2(long arg)
{
	printf(" CMU %ld\n", Lt_arg_2() * arg);
}

static void PrCMUz(void)
{
	printf(" CMU\n");
}

static void PrCOMl2(long arg)
{
	printf(" COM %ld\n", Lt_arg_2() * arg);
}

static void PrCOMz(void)
{
	printf(" COM\n");
}

static void PrCSAl2(long arg)
{
	printf(" CSA %ld\n", Lt_arg_2() * arg);
}

static void PrCSAm(long arg)
{
	printf(" CSA %ld\n", arg);
}

static void PrCSAz(void)
{
	printf(" CSA\n");
}

static void PrCSBl2(long arg)
{
	printf(" CSB %ld\n", Lt_arg_2() * arg);
}

static void PrCSBm(long arg)
{
	printf(" CSB %ld\n", arg);
}

static void PrCSBz(void)
{
	printf(" CSB\n");
}

static void PrCUFz(void)
{
	printf(" CUF\n");
}

static void PrCUIz(void)
{
	printf(" CUI\n");
}

static void PrCUUz(void)
{
	printf(" CUU\n");
}

static void PrDCHz(void)
{
	printf(" DCH\n");
}

static void PrDECz(void)
{
	printf(" DEC\n");
}

static void PrDEEl2(long arg)
{
	printf(" DEE %ld\n", Lt_arg_2() * arg);
}

static void PrDEEl4(long arg)
{
	printf(" DEE %ld\n", Lt_arg_4() * arg);
}

static void PrDEEs(long hob, size wfac)
{
	printf(" DEE %ld\n", St_arg(hob) * wfac);
}

static void PrDELn2(long arg)
{
	printf(" DEL %ld\n", Nt_arg_2() * arg);
}

static void PrDELn4(long arg)
{
	printf(" DEL %ld\n", Nt_arg_4() * arg);
}

static void PrDELp2(long arg)
{
	printf(" DEL %ld\n", Pt_arg_2() * arg);
}

static void PrDELp4(long arg)
{
	printf(" DEL %ld\n", Pt_arg_4() * arg);
}

static void PrDELs(long hob, size wfac)
{
	printf(" DEL %ld\n", St_arg(hob) * wfac);
}

static void PrDUPl2(long arg)
{
	printf(" DUP %ld\n", Lt_arg_2() * arg);
}

static void PrDUPm(long arg)
{
	printf(" DUP %ld\n", arg);
}

static void PrDUSl2(long arg)
{
	printf(" DUS %ld\n", Lt_arg_2() * arg);
}

static void PrDUSz(void)
{
	printf(" DUS\n");
}

static void PrDVFl2(long arg)
{
	printf(" DVF %ld\n", Lt_arg_2() * arg);
}

static void PrDVFs(long hob, size wfac)
{
	printf(" DVF %ld\n", St_arg(hob) * wfac);
}

static void PrDVFz(void)
{
	printf(" DVF\n");
}

static void PrDVIl2(long arg)
{
	printf(" DVI %ld\n", Lt_arg_2() * arg);
}

static void PrDVIm(long arg)
{
	printf(" DVI %ld\n", arg);
}

static void PrDVIz(void)
{
	printf(" DVI\n");
}

static void PrDVUl2(long arg)
{
	printf(" DVU %ld\n", Lt_arg_2() * arg);
}

static void PrDVUz(void)
{
	printf(" DVU\n");
}

static void PrEXGl2(long arg)
{
	printf(" EXG %ld\n", Lt_arg_2() * arg);
}

static void PrEXGs(long hob, size wfac)
{
	printf(" EXG %ld\n", St_arg(hob) * wfac);
}

static void PrEXGz(void)
{
	printf(" EXG\n");
}

static void PrFEFl2(long arg)
{
	printf(" FEF %ld\n", Lt_arg_2() * arg);
}

static void PrFEFz(void)
{
	printf(" FEF\n");
}

static void PrFIFl2(long arg)
{
	printf(" FIF %ld\n", Lt_arg_2() * arg);
}

static void PrFIFz(void)
{
	printf(" FIF\n");
}

static void PrFILu(long arg)
{
	printf(" FIL %ld\n", Ut_arg() * arg);
}

static void PrFILl4(long arg)
{
	printf(" FIL %ld\n", Lt_arg_4() * arg);
}

static void PrGTOu(long arg)
{
	printf(" GTO %ld\n", Ut_arg() * arg);
}

static void PrGTOl4(long arg)
{
	printf(" GTO %ld\n", Lt_arg_4() * arg);
}

static void PrINCz(void)
{
	printf(" INC\n");
}

static void PrINEl2(long arg)
{
	printf(" INE %ld\n", Lt_arg_2() * arg);
}

static void PrINEl4(long arg)
{
	printf(" INE %ld\n", Lt_arg_4() * arg);
}

static void PrINEs(long hob, size wfac)
{
	printf(" INE %ld\n", St_arg(hob) * wfac);
}

static void PrINLm(long arg)
{
	printf(" INL %ld\n", arg);
}

static void PrINLn2(long arg)
{
	printf(" INL %ld\n", Nt_arg_2() * arg);
}

static void PrINLn4(long arg)
{
	printf(" INL %ld\n", Nt_arg_4() * arg);
}

static void PrINLp2(long arg)
{
	printf(" INL %ld\n", Pt_arg_2() * arg);
}

static void PrINLp4(long arg)
{
	printf(" INL %ld\n", Pt_arg_4() * arg);
}

static void PrINLs(long hob, size wfac)
{
	printf(" INL %ld\n", St_arg(hob) * wfac);
}

static void PrINNl2(long arg)
{
	printf(" INN %ld\n", Lt_arg_2() * arg);
}

static void PrINNs(long hob, size wfac)
{
	printf(" INN %ld\n", St_arg(hob) * wfac);
}

static void PrINNz(void)
{
	printf(" INN\n");
}

static void PrIORl2(long arg)
{
	printf(" IOR %ld\n", Lt_arg_2() * arg);
}

static void PrIORm(long arg)
{
	printf(" IOR %ld\n", arg);
}

static void PrIORs(long hob, size wfac)
{
	printf(" IOR %ld\n", St_arg(hob) * wfac);
}

static void PrIORz(void)
{
	printf(" IOR\n");
}

static void PrLAEu(long arg)
{
	printf(" LAE %ld\n", Ut_arg() * arg);
}

static void PrLAEl4(long arg)
{
	printf(" LAE %ld\n", Lt_arg_4() * arg);
}

static void PrLAEs(long hob, size wfac)
{
	printf(" LAE %ld\n", St_arg(hob) * wfac);
}

static void PrLALm(long arg)
{
	printf(" LAL %ld\n", arg);
}

static void PrLALn2(long arg)
{
	printf(" LAL %ld\n", Nt_arg_2() * arg);
}

static void PrLALn4(long arg)
{
	printf(" LAL %ld\n", Nt_arg_4() * arg);
}

static void PrLALp2(long arg)
{
	printf(" LAL %ld\n", Pt_arg_2() * arg);
}

static void PrLALp4(long arg)
{
	printf(" LAL %ld\n", Pt_arg_4() * arg);
}

static void PrLALs(long hob, size wfac)
{
	printf(" LAL %ld\n", St_arg(hob) * wfac);
}

static void PrLARl2(long arg)
{
	printf(" LAR %ld\n", Lt_arg_2() * arg);
}

static void PrLARm(long arg)
{
	printf(" LAR %ld\n", arg);
}

static void PrLARz(void)
{
	printf(" LAR\n");
}

static void PrLDCl2(long arg)
{
	printf(" LDC %ld\n", Lt_arg_2() * arg);
}

static void PrLDCl4(long arg)
{
	printf(" LDC %ld\n", Lt_arg_4() * arg);
}

static void PrLDCm(long arg)
{
	printf(" LDC %ld\n", arg);
}

static void PrLDEl2(long arg)
{
	printf(" LDE %ld\n", Lt_arg_2() * arg);
}

static void PrLDEl4(long arg)
{
	printf(" LDE %ld\n", Lt_arg_4() * arg);
}

static void PrLDEs(long hob, size wfac)
{
	printf(" LDE %ld\n", St_arg(hob) * wfac);
}

static void PrLDFl2(long arg)
{
	printf(" LDF %ld\n", Lt_arg_2() * arg);
}

static void PrLDFl4(long arg)
{
	printf(" LDF %ld\n", Lt_arg_4() * arg);
}

static void PrLDLm(long arg)
{
	printf(" LDL %ld\n", arg);
}

static void PrLDLn2(long arg)
{
	printf(" LDL %ld\n", Nt_arg_2() * arg);
}

static void PrLDLn4(long arg)
{
	printf(" LDL %ld\n", Nt_arg_4() * arg);
}

static void PrLDLp2(long arg)
{
	printf(" LDL %ld\n", Pt_arg_2() * arg);
}

static void PrLDLp4(long arg)
{
	printf(" LDL %ld\n", Pt_arg_4() * arg);
}

static void PrLDLs(long hob, size wfac)
{
	printf(" LDL %ld\n", St_arg(hob) * wfac);
}

static void PrLFRl2(long arg)
{
	printf(" LFR %ld\n", Lt_arg_2() * arg);
}

static void PrLFRm(long arg)
{
	printf(" LFR %ld\n", arg);
}

static void PrLFRs(long hob, size wfac)
{
	printf(" LFR %ld\n", St_arg(hob) * wfac);
}

static void PrLILm(long arg)
{
	printf(" LIL %ld\n", arg);
}

static void PrLILn2(long arg)
{
	printf(" LIL %ld\n", Nt_arg_2() * arg);
}

static void PrLILn4(long arg)
{
	printf(" LIL %ld\n", Nt_arg_4() * arg);
}

static void PrLILp2(long arg)
{
	printf(" LIL %ld\n", Pt_arg_2() * arg);
}

static void PrLILp4(long arg)
{
	printf(" LIL %ld\n", Pt_arg_4() * arg);
}

static void PrLILs(long hob, size wfac)
{
	printf(" LIL %ld\n", St_arg(hob) * wfac);
}

static void PrLIMz(void)
{
	printf(" LIM\n");
}

static void PrLINl2(long arg)
{
	printf(" LIN %ld\n", Lt_arg_2() * arg);
}

static void PrLINl4(long arg)
{
	printf(" LIN %ld\n", Lt_arg_4() * arg);
}

static void PrLINs(long hob, size wfac)
{
	printf(" LIN %ld\n", St_arg(hob) * wfac);
}

static void PrLNIz(void)
{
	printf(" LNI\n");
}

static void PrLOCl2(long arg)
{
	printf(" LOC %ld\n", Lt_arg_2() * arg);
}

static void PrLOCl4(long arg)
{
	printf(" LOC %ld\n", Lt_arg_4() * arg);
}

static void PrLOCm(long arg)
{
	printf(" LOC %ld\n", arg);
}

static void PrLOCs(long hob, size wfac)
{
	printf(" LOC %ld\n", St_arg(hob) * wfac);
}

static void PrLOEl2(long arg)
{
	printf(" LOE %ld\n", Lt_arg_2() * arg);
}

static void PrLOEl4(long arg)
{
	printf(" LOE %ld\n", Lt_arg_4() * arg);
}

static void PrLOEs(long hob, size wfac)
{
	printf(" LOE %ld\n", St_arg(hob) * wfac);
}

static void PrLOFl2(long arg)
{
	printf(" LOF %ld\n", Lt_arg_2() * arg);
}

static void PrLOFl4(long arg)
{
	printf(" LOF %ld\n", Lt_arg_4() * arg);
}

static void PrLOFm(long arg)
{
	printf(" LOF %ld\n", arg);
}

static void PrLOFs(long hob, size wfac)
{
	printf(" LOF %ld\n", St_arg(hob) * wfac);
}

static void PrLOIl2(long arg)
{
	printf(" LOI %ld\n", Lt_arg_2() * arg);
}

static void PrLOIl4(long arg)
{
	printf(" LOI %ld\n", Lt_arg_4() * arg);
}

static void PrLOIm(long arg)
{
	printf(" LOI %ld\n", arg);
}

static void PrLOIs(long hob, size wfac)
{
	printf(" LOI %ld\n", St_arg(hob) * wfac);
}

static void PrLOLm(long arg)
{
	printf(" LOL %ld\n", arg);
}

static void PrLOLn2(long arg)
{
	printf(" LOL %ld\n", Nt_arg_2() * arg);
}

static void PrLOLn4(long arg)
{
	printf(" LOL %ld\n", Nt_arg_4() * arg);
}

static void PrLOLp2(long arg)
{
	printf(" LOL %ld\n", Pt_arg_2() * arg);
}

static void PrLOLp4(long arg)
{
	printf(" LOL %ld\n", Pt_arg_4() * arg);
}

static void PrLOLs(long hob, size wfac)
{
	printf(" LOL %ld\n", St_arg(hob) * wfac);
}

static void PrLORs(long hob, size wfac)
{
	printf(" LOR %ld\n", St_arg(hob) * wfac);
}

static void PrLOSl2(long arg)
{
	printf(" LOS %ld\n", Lt_arg_2() * arg);
}

static void PrLOSz(void)
{
	printf(" LOS\n");
}

static void PrLPBz(void)
{
	printf(" LPB\n");
}

static void PrLPIl2(long arg)
{
	printf(" LPI %ld\n", Lt_arg_2() * arg);
}

static void PrLPIl4(long arg)
{
	printf(" LPI %ld\n", Lt_arg_4() * arg);
}

static void PrLXAl2(long arg)
{
	printf(" LXA %ld\n", Lt_arg_2() * arg);
}

static void PrLXAm(long arg)
{
	printf(" LXA %ld\n", arg);
}

static void PrLXLl2(long arg)
{
	printf(" LXL %ld\n", Lt_arg_2() * arg);
}

static void PrLXLm(long arg)
{
	printf(" LXL %ld\n", arg);
}

static void PrMLFl2(long arg)
{
	printf(" MLF %ld\n", Lt_arg_2() * arg);
}

static void PrMLFs(long hob, size wfac)
{
	printf(" MLF %ld\n", St_arg(hob) * wfac);
}

static void PrMLFz(void)
{
	printf(" MLF\n");
}

static void PrMLIl2(long arg)
{
	printf(" MLI %ld\n", Lt_arg_2() * arg);
}

static void PrMLIm(long arg)
{
	printf(" MLI %ld\n", arg);
}

static void PrMLIz(void)
{
	printf(" MLI\n");
}

static void PrMLUl2(long arg)
{
	printf(" MLU %ld\n", Lt_arg_2() * arg);
}

static void PrMLUz(void)
{
	printf(" MLU\n");
}

static void PrMONz(void)
{
	printf(" MON\n");
}

static void PrNGFl2(long arg)
{
	printf(" NGF %ld\n", Lt_arg_2() * arg);
}

static void PrNGFz(void)
{
	printf(" NGF\n");
}

static void PrNGIl2(long arg)
{
	printf(" NGI %ld\n", Lt_arg_2() * arg);
}

static void PrNGIz(void)
{
	printf(" NGI\n");
}

static void PrNOPz(void)
{
	printf(" NOP\n");
}

static void PrRCKl2(long arg)
{
	printf(" RCK %ld\n", Lt_arg_2() * arg);
}

static void PrRCKm(long arg)
{
	printf(" RCK %ld\n", arg);
}

static void PrRCKz(void)
{
	printf(" RCK\n");
}

static void PrRETl2(long arg)
{
	printf(" RET %ld\n", Lt_arg_2() * arg);
}

static void PrRETm(long arg)
{
	printf(" RET %ld\n", arg);
}

static void PrRETs(long hob, size wfac)
{
	printf(" RET %ld\n", St_arg(hob) * wfac);
}

static void PrRMIl2(long arg)
{
	printf(" RMI %ld\n", Lt_arg_2() * arg);
}

static void PrRMIm(long arg)
{
	printf(" RMI %ld\n", arg);
}

static void PrRMIz(void)
{
	printf(" RMI\n");
}

static void PrRMUl2(long arg)
{
	printf(" RMU %ld\n", Lt_arg_2() * arg);
}

static void PrRMUz(void)
{
	printf(" RMU\n");
}

static void PrROLl2(long arg)
{
	printf(" ROL %ld\n", Lt_arg_2() * arg);
}

static void PrROLz(void)
{
	printf(" ROL\n");
}

static void PrRORl2(long arg)
{
	printf(" ROR %ld\n", Lt_arg_2() * arg);
}

static void PrRORz(void)
{
	printf(" ROR\n");
}

static void PrRTTz(void)
{
	printf(" RTT\n");
}

static void PrSARl2(long arg)
{
	printf(" SAR %ld\n", Lt_arg_2() * arg);
}

static void PrSARm(long arg)
{
	printf(" SAR %ld\n", arg);
}

static void PrSARz(void)
{
	printf(" SAR\n");
}

static void PrSBFl2(long arg)
{
	printf(" SBF %ld\n", Lt_arg_2() * arg);
}

static void PrSBFs(long hob, size wfac)
{
	printf(" SBF %ld\n", St_arg(hob) * wfac);
}

static void PrSBFz(void)
{
	printf(" SBF\n");
}

static void PrSBIl2(long arg)
{
	printf(" SBI %ld\n", Lt_arg_2() * arg);
}

static void PrSBIm(long arg)
{
	printf(" SBI %ld\n", arg);
}

static void PrSBIz(void)
{
	printf(" SBI\n");
}

static void PrSBSl2(long arg)
{
	printf(" SBS %ld\n", Lt_arg_2() * arg);
}

static void PrSBSz(void)
{
	printf(" SBS\n");
}

static void PrSBUl2(long arg)
{
	printf(" SBU %ld\n", Lt_arg_2() * arg);
}

static void PrSBUz(void)
{
	printf(" SBU\n");
}

static void PrSDEu(long arg)
{
	printf(" SDE %ld\n", Ut_arg() * arg);
}

static void PrSDEl4(long arg)
{
	printf(" SDE %ld\n", Lt_arg_4() * arg);
}

static void PrSDFl2(long arg)
{
	printf(" SDF %ld\n", Lt_arg_2() * arg);
}

static void PrSDFl4(long arg)
{
	printf(" SDF %ld\n", Lt_arg_4() * arg);
}

static void PrSDLn2(long arg)
{
	printf(" SDL %ld\n", Nt_arg_2() * arg);
}

static void PrSDLn4(long arg)
{
	printf(" SDL %ld\n", Nt_arg_4() * arg);
}

static void PrSDLp2(long arg)
{
	printf(" SDL %ld\n", Pt_arg_2() * arg);
}

static void PrSDLp4(long arg)
{
	printf(" SDL %ld\n", Pt_arg_4() * arg);
}

static void PrSDLs(long hob, size wfac)
{
	printf(" SDL %ld\n", St_arg(hob) * wfac);
}

static void PrSETl2(long arg)
{
	printf(" SET %ld\n", Lt_arg_2() * arg);
}

static void PrSETs(long hob, size wfac)
{
	printf(" SET %ld\n", St_arg(hob) * wfac);
}

static void PrSETz(void)
{
	printf(" SET\n");
}

static void PrSIGz(void)
{
	printf(" SIG\n");
}

static void PrSILn2(long arg)
{
	printf(" SIL %ld\n", Nt_arg_2() * arg);
}

static void PrSILn4(long arg)
{
	printf(" SIL %ld\n", Nt_arg_4() * arg);
}

static void PrSILp2(long arg)
{
	printf(" SIL %ld\n", Pt_arg_2() * arg);
}

static void PrSILp4(long arg)
{
	printf(" SIL %ld\n", Pt_arg_4() * arg);
}

static void PrSILs(long hob, size wfac)
{
	printf(" SIL %ld\n", St_arg(hob) * wfac);
}

static void PrSIMz(void)
{
	printf(" SIM\n");
}

static void PrSLIl2(long arg)
{
	printf(" SLI %ld\n", Lt_arg_2() * arg);
}

static void PrSLIm(long arg)
{
	printf(" SLI %ld\n", arg);
}

static void PrSLIz(void)
{
	printf(" SLI\n");
}

static void PrSLUl2(long arg)
{
	printf(" SLU %ld\n", Lt_arg_2() * arg);
}

static void PrSLUz(void)
{
	printf(" SLU\n");
}

static void PrSRIl2(long arg)
{
	printf(" SRI %ld\n", Lt_arg_2() * arg);
}

static void PrSRIz(void)
{
	printf(" SRI\n");
}

static void PrSRUl2(long arg)
{
	printf(" SRU %ld\n", Lt_arg_2() * arg);
}

static void PrSRUz(void)
{
	printf(" SRU\n");
}

static void PrSTEl2(long arg)
{
	printf(" STE %ld\n", Lt_arg_2() * arg);
}

static void PrSTEl4(long arg)
{
	printf(" STE %ld\n", Lt_arg_4() * arg);
}

static void PrSTEs(long hob, size wfac)
{
	printf(" STE %ld\n", St_arg(hob) * wfac);
}

static void PrSTFl2(long arg)
{
	printf(" STF %ld\n", Lt_arg_2() * arg);
}

static void PrSTFl4(long arg)
{
	printf(" STF %ld\n", Lt_arg_4() * arg);
}

static void PrSTFm(long arg)
{
	printf(" STF %ld\n", arg);
}

static void PrSTFs(long hob, size wfac)
{
	printf(" STF %ld\n", St_arg(hob) * wfac);
}

static void PrSTIl2(long arg)
{
	printf(" STI %ld\n", Lt_arg_2() * arg);
}

static void PrSTIl4(long arg)
{
	printf(" STI %ld\n", Lt_arg_4() * arg);
}

static void PrSTIm(long arg)
{
	printf(" STI %ld\n", arg);
}

static void PrSTIs(long hob, size wfac)
{
	printf(" STI %ld\n", St_arg(hob) * wfac);
}

static void PrSTLm(long arg)
{
	printf(" STL %ld\n", arg);
}

static void PrSTLn2(long arg)
{
	printf(" STL %ld\n", Nt_arg_2() * arg);
}

static void PrSTLn4(long arg)
{
	printf(" STL %ld\n", Nt_arg_4() * arg);
}

static void PrSTLp2(long arg)
{
	printf(" STL %ld\n", Pt_arg_2() * arg);
}

static void PrSTLp4(long arg)
{
	printf(" STL %ld\n", Pt_arg_4() * arg);
}

static void PrSTLs(long hob, size wfac)
{
	printf(" STL %ld\n", St_arg(hob) * wfac);
}

static void PrSTRs(long hob, size wfac)
{
	printf(" STR %ld\n", St_arg(hob) * wfac);
}

static void PrSTSl2(long arg)
{
	printf(" STS %ld\n", Lt_arg_2() * arg);
}

static void PrSTSz(void)
{
	printf(" STS\n");
}

static void PrTEQz(void)
{
	printf(" TEQ\n");
}

static void PrTGEz(void)
{
	printf(" TGE\n");
}

static void PrTGTz(void)
{
	printf(" TGT\n");
}

static void PrTLEz(void)
{
	printf(" TLE\n");
}

static void PrTLTz(void)
{
	printf(" TLT\n");
}

static void PrTNEz(void)
{
	printf(" TNE\n");
}

static void PrTRPz(void)
{
	printf(" TRP\n");
}

static void PrXORl2(long arg)
{
	printf(" XOR %ld\n", Lt_arg_2() * arg);
}

static void PrXORz(void)
{
	printf(" XOR\n");
}

static void PrZEQl2(long arg)
{
	printf(" ZEQ %ld\n", Lt_arg_2() * arg);
}

static void PrZEQl4(long arg)
{
	printf(" ZEQ %ld\n", Lt_arg_4() * arg);
}

static void PrZEQs(long hob, size wfac)
{
	printf(" ZEQ %ld\n", St_arg(hob) * wfac);
}

static void PrZERl2(long arg)
{
	printf(" ZER %ld\n", Lt_arg_2() * arg);
}

static void PrZERs(long hob, size wfac)
{
	printf(" ZER %ld\n", St_arg(hob) * wfac);
}

static void PrZERz(void)
{
	printf(" ZER\n");
}

static void PrZGEl2(long arg)
{
	printf(" ZGE %ld\n", Lt_arg_2() * arg);
}

static void PrZGEl4(long arg)
{
	printf(" ZGE %ld\n", Lt_arg_4() * arg);
}

static void PrZGEs(long hob, size wfac)
{
	printf(" ZGE %ld\n", St_arg(hob) * wfac);
}

static void PrZGTl2(long arg)
{
	printf(" ZGT %ld\n", Lt_arg_2() * arg);
}

static void PrZGTl4(long arg)
{
	printf(" ZGT %ld\n", Lt_arg_4() * arg);
}

static void PrZGTs(long hob, size wfac)
{
	printf(" ZGT %ld\n", St_arg(hob) * wfac);
}

static void PrZLEl2(long arg)
{
	printf(" ZLE %ld\n", Lt_arg_2() * arg);
}

static void PrZLEl4(long arg)
{
	printf(" ZLE %ld\n", Lt_arg_4() * arg);
}

static void PrZLEs(long hob, size wfac)
{
	printf(" ZLE %ld\n", St_arg(hob) * wfac);
}

static void PrZLTl2(long arg)
{
	printf(" ZLT %ld\n", Lt_arg_2() * arg);
}

static void PrZLTl4(long arg)
{
	printf(" ZLT %ld\n", Lt_arg_4() * arg);
}

static void PrZLTs(long hob, size wfac)
{
	printf(" ZLT %ld\n", St_arg(hob) * wfac);
}

static void PrZNEl2(long arg)
{
	printf(" ZNE %ld\n", Lt_arg_2() * arg);
}

static void PrZNEl4(long arg)
{
	printf(" ZNE %ld\n", Lt_arg_4() * arg);
}

static void PrZNEs(long hob, size wfac)
{
	printf(" ZNE %ld\n", St_arg(hob) * wfac);
}

static void PrZREl2(long arg)
{
	printf(" ZRE %ld\n", Lt_arg_2() * arg);
}

static void PrZREl4(long arg)
{
	printf(" ZRE %ld\n", Lt_arg_4() * arg);
}

static void PrZREs(long hob, size wfac)
{
	printf(" ZRE %ld\n", St_arg(hob) * wfac);
}

static void PrZRFl2(long arg)
{
	printf(" ZRF %ld\n", Lt_arg_2() * arg);
}

static void PrZRFz(void)
{
	printf(" ZRF\n");
}

static void PrZRLm(long arg)
{
	printf(" ZRL %ld\n", arg);
}

static void PrZRLn2(long arg)
{
	printf(" ZRL %ld\n", Nt_arg_2() * arg);
}

static void PrZRLn4(long arg)
{
	printf(" ZRL %ld\n", Nt_arg_4() * arg);
}

static void PrZRLp2(long arg)
{
	printf(" ZRL %ld\n", Pt_arg_2() * arg);
}

static void PrZRLp4(long arg)
{
	printf(" ZRL %ld\n", Pt_arg_4() * arg);
}

static void PrZRLs(long hob, size wfac)
{
	printf(" ZRL %ld\n", St_arg(hob) * wfac);
}

/* Original code! */

/******** Disassembly of Text Segment ********/

struct ep
{ /* procedure entry points */
	int ep_idf;
	ptr ep_ep;
	size ep_nloc;
};

void disassemble(void)
{
	ptr low = 0;
	ptr high = DB;
	int idf;
	int cnt;
	struct ep* ep; /* list of entry points */

	/* collect the entry points */
	ep = (struct ep*)Malloc((size)(NProc * sizeof(struct ep)), "entry points");
	for (idf = 0; idf < NProc; idf++)
	{
		struct proc* pr = &proctab[idf];

		ep[idf].ep_idf = idf;
		ep[idf].ep_ep = pr->pr_ep;
		ep[idf].ep_nloc = pr->pr_nloc;
	}

	/* a very naive sorting algorithm */
	for (idf = 0; idf < NProc; idf++)
	{
		int jdf;

		for (jdf = 0; jdf < NProc; jdf++)
		{
			if ((ep[idf].ep_ep < ep[jdf].ep_ep) != (idf < jdf))
			{
				struct ep p;
				p = ep[idf];
				ep[idf] = ep[jdf];
				ep[jdf] = p;
			}
		}
	}

	TC = low;
	cnt = 0;
	idf = 0;
	while (TC < high)
	{
		if (cnt == 0)
		{
			printf("%lu\n", TC);
		}
		cnt = (cnt + 1) % 10;

		if (idf < NProc && TC >= ep[idf].ep_ep)
		{
			struct ep* p = &ep[idf];

			printf(
			    "P[%d]+%lu:	; %ld %s\n", p->ep_idf, TC - p->ep_ep, p->ep_nloc,
			    p->ep_nloc == 1 ? "local" : "locals");
			idf++;
		}

		do_pr_instr(nextTCbyte()); /* advances TC */
	}
}

/* See switch.c */

static void do_pr_instr(unsigned int opcode)
{
	switch (opcode)
	{
#include "PrCases" /* for the muscle */
		case SECONDARY:
			do_pr_instr(SEC_BASE + nextTCbyte());
			break;
		case TERTIARY:
			do_pr_instr(TERT_BASE + nextTCbyte());
			break;
		default:
			printf(">>>> bad opcode %u at PC = %lu <<<<\n", opcode, TC);
			break;
	}
}
