for _, plat in ipairs(vars.plats) do
	acklibrary {
		name = "lib_"..plat,
		srcs = {
			"./adi.s",
			"./and.s",
			"./blm.s",
			"./cii.s",
			"./cmi4.s",
			"./cms.s",
			"./cmu4.s",
			"./com.s",
			"./csa2.s",
			"./csa4.s",
			"./csb2.s",
			"./csb4.s",
			"./cuu.s",
			"./dup.s",
			"./dvi4.s",
			"./dvi.s",
			"./dvu4.s",
			"./dvu.s",
			"./error.s",
			"./exg.s",
			"./fat.s",
			"./fp8087.s",
			"./gto.s",
			"./iaar.s",
			"./ilar.s",
			"./inn.s",
			"./ior.s",
			"./isar.s",
			"./lar2.s",
			"./lfr6.s",
			"./lfr8.s",
			"./loi.s",
			"./mli4.s",
			"./mli.s",
			"./mon.s",
			"./ngi.s",
			"./nop.s",
			"./print.s",
			"./rck.s",
			"./ret6.s",
			"./ret8.s",
			"./retarea.s",
			"./return.s",
			"./rmi4.s",
			"./rmi.s",
			"./rmu4.s",
			"./rmu.s",
			"./rol.s",
			"./ror.s",
			"./sar2.s",
			"./sbi.s",
			"./set.s",
			"./sli.s",
			"./sri.s",
			"./sti.s",
			"./strhp.s",
			"./trp.s",
			"./unknown.s",
			"./xor.s",
		},
		vars = { plat = plat },
	}
end

