bundle {
	name = "srcs",
	srcs = {
		"./aar_e.e",
		"./and_e.e",
		"./andv_e.e",
		"./brk_c.c",
		"./bss_e.c",
		"./calloc_c.c",
		"./cii_e.e",
		"./cmi_e.e",
		"./cms_e.e",
		"./cmu_e.e",
		"./csa_e.c",
		"./csb_e.c",
		"./_dummy_e.c",
		"./dup_e.e",
		"./exg_e.e",
		"./inn_e.e",
		"./intadd_e.c",
		"./intaddl_e.c",
		"./intcmp_e.c",
		"./intmul_e.c",
		"./intdiv_e.c",
		"./intdivl_e.c",
		"./intrem_e.c",
		"./intshift_e.c",
		"./intsub_e.c",
		"./ior_e.e",
		"./iorv_e.e",
		"./lar_e.e",
		"./rck_e.e",
		--"./rotate_e.e",
		"./sar_e.e",
		"./set_e.e",
		"./setjmp_c.c",
		"./structcopy_e.c",
		"./xor_e.e",
		"./xorv_e.e",
	}
}


