.TH PRINT 3 "$Revision$"
.ad
.SH NAME
print, fprint, doprnt -- very simple formatted-output routines
.SH SYNOPSIS
.nf
.B #include <system.h>
.B #include <print.h>
.PP
.B int _format(char *buf, char *format, va_lsit args)
.fi
.SH DESCRIPTION
The
.I _format
routine builds the string, but does not null-terminate it. It returns the
length of the string.
.SH FILES
.nf
~em/modules/lib/libprint.a
.fi
.SH MODULES
system(3), string(3)
.SH DIAGNOSTICS
.PP
Each illegal conversion specification is replaced by the string "<bad\ format>".
.SH BUGS
The maximum length of the string to be printed is 1024 characters.
.SH SEE ALSO
printf(3)
