#define C_lae_dnam _1_C_lae_dnam
#define C_lae_dlb _2_C_lae_dlb
#define C_sde_dnam _3_C_sde_dnam
#define C_sde_dlb _4_C_sde_dlb
#define C_zre_dnam _5_C_zre_dnam
#define C_zre_dlb _6_C_zre_dlb
#define C_hol_dnam _7_C_hol_dnam
#define C_hol_dlb _8_C_hol_dlb
#define C_hol_icon _9_C_hol_icon
#define C_hol_ilb _10_C_hol_ilb
#define C_bss_dnam _11_C_bss_dnam
#define C_bss_dlb _12_C_bss_dlb
#define C_bss_icon _13_C_bss_icon
#define C_bss_ilb _14_C_bss_ilb
#define C_con_dnam _15_C_con_dnam
#define C_con_dlb _16_C_con_dlb
#define C_con_icon _17_C_con_icon
#define C_con_ilb _18_C_con_ilb
#define C_gto_dnam _19_C_gto_dnam
#define C_gto_dlb _20_C_gto_dlb
#define C_ine_dnam _21_C_ine_dnam
#define C_ine_dlb _22_C_ine_dlb
#define C_rom_dnam _23_C_rom_dnam
#define C_rom_dlb _24_C_rom_dlb
#define C_ina_dnam _25_C_ina_dnam
#define C_ina_dlb _26_C_ina_dlb
#define C_rom_icon _27_C_rom_icon
#define C_rom_ilb _28_C_rom_ilb
#define C_ste_dnam _29_C_ste_dnam
#define C_ste_dlb _30_C_ste_dlb
#define C_fil_dnam _31_C_fil_dnam
#define C_fil_dlb _32_C_fil_dlb
#define C_lde_dnam _33_C_lde_dnam
#define C_lde_dlb _34_C_lde_dlb
#define C_loe_dnam _35_C_loe_dnam
#define C_loe_dlb _36_C_loe_dlb
#define C_exa_dnam _37_C_exa_dnam
#define C_exa_dlb _38_C_exa_dlb
#define C_dee_dnam _39_C_dee_dnam
#define C_dee_dlb _40_C_dee_dlb
