#define O_lae_dnam _1_O_lae_dnam
#define O_lae_dlb _2_O_lae_dlb
#define O_sde_dnam _3_O_sde_dnam
#define O_sde_dlb _4_O_sde_dlb
#define O_zre_dnam _5_O_zre_dnam
#define O_zre_dlb _6_O_zre_dlb
#define O_hol_dnam _7_O_hol_dnam
#define O_hol_dlb _8_O_hol_dlb
#define O_hol_icon _9_O_hol_icon
#define O_hol_ilb _10_O_hol_ilb
#define O_bss_dnam _11_O_bss_dnam
#define O_bss_dlb _12_O_bss_dlb
#define O_bss_icon _13_O_bss_icon
#define O_bss_ilb _14_O_bss_ilb
#define O_con_dnam _15_O_con_dnam
#define O_con_dlb _16_O_con_dlb
#define O_con_icon _17_O_con_icon
#define O_con_ilb _18_O_con_ilb
#define O_gto_dnam _19_O_gto_dnam
#define O_gto_dlb _20_O_gto_dlb
#define O_ine_dnam _21_O_ine_dnam
#define O_ine_dlb _22_O_ine_dlb
#define O_rom_dnam _23_O_rom_dnam
#define O_rom_dlb _24_O_rom_dlb
#define O_ina_dnam _25_O_ina_dnam
#define O_ina_dlb _26_O_ina_dlb
#define O_rom_icon _27_O_rom_icon
#define O_rom_ilb _28_O_rom_ilb
#define O_ste_dnam _29_O_ste_dnam
#define O_ste_dlb _30_O_ste_dlb
#define O_fil_dnam _31_O_fil_dnam
#define O_fil_dlb _32_O_fil_dlb
#define O_lde_dnam _33_O_lde_dnam
#define O_lde_dlb _34_O_lde_dlb
#define O_loe_dnam _35_O_loe_dnam
#define O_loe_dlb _36_O_loe_dlb
#define O_exa_dnam _37_O_exa_dnam
#define O_exa_dlb _38_O_exa_dlb
#define O_dee_dnam _39_O_dee_dnam
#define O_dee_dlb _40_O_dee_dlb
