#define C_insertpart	O_insertpart
#define C_beginpart	O_beginpart
#define C_endpart	O_endpart
#define C_aar	O_aar
#define C_aar_narg	O_aar_narg
#define C_adf	O_adf
#define C_adf_narg	O_adf_narg
#define C_adi	O_adi
#define C_adi_narg	O_adi_narg
#define C_adp	O_adp
#define C_ads	O_ads
#define C_ads_narg	O_ads_narg
#define C_adu	O_adu
#define C_adu_narg	O_adu_narg
#define C_and	O_and
#define C_and_narg	O_and_narg
#define C_asp	O_asp
#define C_ass	O_ass
#define C_ass_narg	O_ass_narg
#define C_beq	O_beq
#define C_bge	O_bge
#define C_bgt	O_bgt
#define C_ble	O_ble
#define C_blm	O_blm
#define C_bls	O_bls
#define C_bls_narg	O_bls_narg
#define C_blt	O_blt
#define C_bne	O_bne
#define C_bra	O_bra
#define C_bss_cst	O_bss_cst
#define C_bss_fcon	O_bss_fcon
#define C_bss_pnam	O_bss_pnam
#define C_bss_ucon	O_bss_ucon
#define C_cai	O_cai
#define C_cal	O_cal
#define C_cff	O_cff
#define C_cfi	O_cfi
#define C_cfu	O_cfu
#define C_cif	O_cif
#define C_cii	O_cii
#define C_ciu	O_ciu
#define C_close	O_close
#define C_cmf	O_cmf
#define C_cmf_narg	O_cmf_narg
#define C_cmi	O_cmi
#define C_cmi_narg	O_cmi_narg
#define C_cmp	O_cmp
#define C_cms	O_cms
#define C_cms_narg	O_cms_narg
#define C_cmu	O_cmu
#define C_cmu_narg	O_cmu_narg
#define C_com	O_com
#define C_com_narg	O_com_narg
#define C_con_cst	O_con_cst
#define C_con_fcon	O_con_fcon
#define C_con_pnam	O_con_pnam
#define C_con_scon	O_con_scon
#define C_con_ucon	O_con_ucon
#define C_csa	O_csa
#define C_csa_narg	O_csa_narg
#define C_csb	O_csb
#define C_csb_narg	O_csb_narg
#define C_cst	O_cst
#define C_cuf	O_cuf
#define C_cui	O_cui
#define C_cuu	O_cuu
#define C_dch	O_dch
#define C_dec	O_dec
#define C_dee	O_dee
#define C_del	O_del
#define C_df_dlb	O_df_dlb
#define C_df_dnam	O_df_dnam
#define C_df_ilb	O_df_ilb
#define C_dlb	O_dlb
#define C_dnam	O_dnam
#define C_dup	O_dup
#define C_dus	O_dus
#define C_dus_narg	O_dus_narg
#define C_dvf	O_dvf
#define C_dvf_narg	O_dvf_narg
#define C_dvi	O_dvi
#define C_dvi_narg	O_dvi_narg
#define C_dvu	O_dvu
#define C_dvu_narg	O_dvu_narg
#define C_end	O_end
#define C_end_narg	O_end_narg
#define C_exc	O_exc
#define C_exg	O_exg
#define C_exg_narg	O_exg_narg
#define C_exp	O_exp
#define C_fcon	O_fcon
#define C_fef	O_fef
#define C_fef_narg	O_fef_narg
#define C_fif	O_fif
#define C_fif_narg	O_fif_narg
#define C_fil	O_fil
#define C_gto	O_gto
#define C_hol_cst	O_hol_cst
#define C_hol_fcon	O_hol_fcon
#define C_hol_pnam	O_hol_pnam
#define C_hol_ucon	O_hol_ucon
#define C_icon	O_icon
#define C_ilb	O_ilb
#define C_inc	O_inc
#define C_ine	O_ine
#define C_init	O_init
#define C_inl	O_inl
#define C_inn	O_inn
#define C_inn_narg	O_inn_narg
#define C_inp	O_inp
#define C_ior	O_ior
#define C_ior_narg	O_ior_narg
#define C_lae	O_lae
#define C_lal	O_lal
#define C_lar	O_lar
#define C_lar_narg	O_lar_narg
#define C_ldc	O_ldc
#define C_lde	O_lde
#define C_ldf	O_ldf
#define C_ldl	O_ldl
#define C_lfr	O_lfr
#define C_lil	O_lil
#define C_lim	O_lim
#define C_lin	O_lin
#define C_lni	O_lni
#define C_loc	O_loc
#define C_loe	O_loe
#define C_lof	O_lof
#define C_loi	O_loi
#define C_lol	O_lol
#define C_lor	O_lor
#define C_los	O_los
#define C_los_narg	O_los_narg
#define C_lpb	O_lpb
#define C_lpi	O_lpi
#define C_lxa	O_lxa
#define C_lxl	O_lxl
#define C_magic	O_magic
#define C_mes_begin	O_mes_begin
#define C_mes_end	O_mes_end
#define C_mlf	O_mlf
#define C_mlf_narg	O_mlf_narg
#define C_mli	O_mli
#define C_mli_narg	O_mli_narg
#define C_mlu	O_mlu
#define C_mlu_narg	O_mlu_narg
#define C_mon	O_mon
#define C_ngf	O_ngf
#define C_ngf_narg	O_ngf_narg
#define C_ngi	O_ngi
#define C_ngi_narg	O_ngi_narg
#define C_nop	O_nop
#define C_open	O_open
#define C_pnam	O_pnam
#define C_pro	O_pro
#define C_pro_narg	O_pro_narg
#define C_rck	O_rck
#define C_rck_narg	O_rck_narg
#define C_ret	O_ret
#define C_rmi	O_rmi
#define C_rmi_narg	O_rmi_narg
#define C_rmu	O_rmu
#define C_rmu_narg	O_rmu_narg
#define C_rol	O_rol
#define C_rol_narg	O_rol_narg
#define C_rom_cst	O_rom_cst
#define C_rom_fcon	O_rom_fcon
#define C_rom_pnam	O_rom_pnam
#define C_rom_scon	O_rom_scon
#define C_rom_ucon	O_rom_ucon
#define C_ror	O_ror
#define C_ror_narg	O_ror_narg
#define C_rtt	O_rtt
#define C_sar	O_sar
#define C_sar_narg	O_sar_narg
#define C_sbf	O_sbf
#define C_sbf_narg	O_sbf_narg
#define C_sbi	O_sbi
#define C_sbi_narg	O_sbi_narg
#define C_sbs	O_sbs
#define C_sbs_narg	O_sbs_narg
#define C_sbu	O_sbu
#define C_sbu_narg	O_sbu_narg
#define C_scon	O_scon
#define C_sde	O_sde
#define C_sdf	O_sdf
#define C_sdl	O_sdl
#define C_set	O_set
#define C_set_narg	O_set_narg
#define C_sig	O_sig
#define C_sil	O_sil
#define C_sim	O_sim
#define C_sli	O_sli
#define C_sli_narg	O_sli_narg
#define C_slu	O_slu
#define C_slu_narg	O_slu_narg
#define C_sri	O_sri
#define C_sri_narg	O_sri_narg
#define C_sru	O_sru
#define C_sru_narg	O_sru_narg
#define C_ste	O_ste
#define C_stf	O_stf
#define C_sti	O_sti
#define C_stl	O_stl
#define C_str	O_str
#define C_sts	O_sts
#define C_sts_narg	O_sts_narg
#define C_teq	O_teq
#define C_tge	O_tge
#define C_tgt	O_tgt
#define C_tle	O_tle
#define C_tlt	O_tlt
#define C_tne	O_tne
#define C_trp	O_trp
#define C_ucon	O_ucon
#define C_xor	O_xor
#define C_xor_narg	O_xor_narg
#define C_zeq	O_zeq
#define C_zer	O_zer
#define C_zer_narg	O_zer_narg
#define C_zge	O_zge
#define C_zgt	O_zgt
#define C_zle	O_zle
#define C_zlt	O_zlt
#define C_zne	O_zne
#define C_zre	O_zre
#define C_zrf	O_zrf
#define C_zrf_narg	O_zrf_narg
#define C_zrl	O_zrl

#define C_hol_ilb	O_hol_ilb
#define C_bss_dnam	O_bss_dnam
#define C_bss_dlb	O_bss_dlb
#define C_bss_icon	O_bss_icon
#define C_bss_ilb	O_bss_ilb
#define C_con_dnam	O_con_dnam
#define C_con_dlb	O_con_dlb
#define C_con_icon	O_con_icon
#define C_con_ilb	O_con_ilb
#define C_gto_dnam	O_gto_dnam
#define C_lae_dnam	O_lae_dnam
#define C_gto_dlb	O_gto_dlb
#define C_ine_dnam	O_ine_dnam
#define C_ine_dlb	O_ine_dlb
#define C_rom_dnam	O_rom_dnam
#define C_rom_dlb	O_rom_dlb
#define C_ina_dnam	O_ina_dnam
#define C_ina_dlb	O_ina_dlb
#define C_rom_icon	O_rom_icon
#define C_rom_ilb	O_rom_ilb
#define C_ste_dnam	O_ste_dnam
#define C_lae_dlb	O_lae_dlb
#define C_ste_dlb	O_ste_dlb
#define C_fil_dnam	O_fil_dnam
#define C_fil_dlb	O_fil_dlb
#define C_lde_dnam	O_lde_dnam
#define C_lde_dlb	O_lde_dlb
#define C_loe_dnam	O_loe_dnam
#define C_loe_dlb	O_loe_dlb
#define C_exa_dnam	O_exa_dnam
#define C_exa_dlb	O_exa_dlb
#define C_dee_dnam	O_dee_dnam
#define C_sde_dnam	O_sde_dnam
#define C_dee_dlb	O_dee_dlb
#define C_sde_dlb	O_sde_dlb
#define C_zre_dnam	O_zre_dnam
#define C_zre_dlb	O_zre_dlb
#define C_hol_dnam	O_hol_dnam
#define C_hol_dlb	O_hol_dlb
#define C_hol_icon	O_hol_icon
