.TH CCLASH 1 "$Revision$"
.ad
.SH NAME
cclash  \-  report clashing identifiers in C-programs
.SH SYNOPSIS
.B cclash
[ -l<length> ] [ -c | -m ]
[ file ... ]
.SH DESCRIPTION
.I Cclash
prints all identifiers that don't differ in the first <length> characters.
The default value for <length> is 8.
.PP
The
.B -m
option indicates that #define's must be generated for clashing identifiers.
This is of course only useful if your preprocessor can distinguish between
them.
.PP
The
.B -c
option indicates that a oldname=newname line must be generated for each
clashing identifier. This is useful input for
.IR cid (1).
.SH "SEE ALSO"
cid(1)
