.TH CID 1 "$Revision$"
.ad
.SH NAME
cid \- change identifiers not occurring in C comment, strings and
character constants.
.SH SYNOPSIS
.B cid
[options] [file ..]
.SH DESCRIPTION
.I Cid
copies the files, or standard input if no files are specified, to
standard output replacing the specified identifiers
by some text, defined by the caller in an option or on a file.
.br
.I Options
is a list of one or more of the following options:
.IP \fB\-D\fP\fIname\fP=\fItext\fP
.br
replace each occurence of \fIname\fP by \fItext\fP.
.I Text
may be empty, in which case the identifier is deleted.
.IP \fB\-D\fP\fIname\fP
.br
Delete all occurences of \fIname\fP.
.IP \fB\-F\fP\fIfile\fP
.br
Read substitute commands of the form "\fIname\fP=\fItext\fP", each on
a single line, from file \fIfile\fP.
.SH SEE ALSO
prid(1), cclash(1)
.SH DIAGNOSTICS
Supposed to be self explanatory.
.SH BUGS
The syntax of the substitute definitions is not (well) checked.
