.TH MKDEP 1 "$Revision$"
.ad
.SH NAME
mkdep \- dependency generator for C-programs
.SH SYNOPSYS
.B mkdep
[ -d ] file ...
.SH DESCRIPTION
.I Mkdep
scans the files in the argument list for C-preprocessor lines of the form
.nf
	#include "\fIfile1\fP"
.fi
and produces for each file \fIarg\fR in the argument list lines of the form
.nf
	\fIarg\fR: \fIfile1\fR
	\fIarg\fR: \fIfile2\fR
	...
.fi
where \fIfile1\fR, \fIfile2\fR, etc. are filenames included by \fIarg\fR, or
by a file included by \fIarg\fR, etc.
.PP
The \fB-d\fP suppresses the \fIarg\fR: part.
.PP
Only files in the current directory are scanned.
.SH "SEE ALSO"
make(1)
.SH BUGS
Should be able to handle files from other directories
