/*
 * (c) copyright 1987 by the Vrije Universiteit, Amsterdam, The Netherlands.
 * See the copyright notice in the ACK home directory, in the file "Copyright".
 */
#define	indir	 0.
#define	exit	 1.
#define	fork	 2.
#define	read	 3.
#define	write	 4.
#define	open	 5.
#define	close	 6.
#define	wait	 7.
#define	creat	 8.
#define	link	 9.
#define	unlink	 10.
#define	exec	 11.
#define	chdir	 12.
#define	time	 13.
#define	mknod	 14.
#define	chmod	 15.
#define	chown	 16.
#define	break	 17.
#define	stat	 18.
#define	lseek	 19.
#define	getpid	 20.
#define	mount	 21.
#define	umount	 22.
#define	setuid	 23.
#define	getuid	 24.
#define	stime	 25.
#define	ptrace	 26.
#define	alarm	 27.
#define	fstat	 28.
#define	pause	 29.
#define	utime	 30.
#define	smdate	 30.
#define	stty	 31.
#define	gtty	 32.
#define	access	 33.
#define	nice	 34.
#define	sleep	 35.
#define	ftime	 35.
#define	sync	 36.
#define	kill	 37.
#define	csw	 38.
#define	setpgrp	 39.
#define	dup	 41.
#define	pipe	 42.
#define	times	 43.
#define	profil	 44.
#define	getgrp	 45.
#define	setgid	 46.
#define	getgid	 47.
#define	signal	 48.
#define	rtp	 49.
#define	setgrp	 50.
#define	acct	 51.
#define	phys	 52.
#define	lock	 53.
#define	ioctl	 54.
#define	reboot	 55.
#define	mpx	 56.
#define	vfork	 57.
#define	setinf	 59.
#define	exece	 59.
#define	local	 58.
#define	umask	 60.
#define	getinf	 60.
#define	chroot	 61.

#define	login	  1.
#define	lstat	  2.
#define	submit	  3.
#define	nostk	  4.
#define	killbkg	  5.
#define	killpg	  6.
#define	renice	  7.
#define	fetchi	  8.
#define	ucall	  9.
#define	quota	 10.
#define	qfstat	 11.
#define	qstat	 12.
#define	gldav	 14.
#define	fperr	 15.
#define	vhangup	 16.
#define	symlink	 29.
#define	readlink	 30.

#define	select	 18.
#define	gethost	 19.
#define	sethost	 20.
#define	socket	 21.
#define	connect	 22.
#define	accept	 23.
#define	send	 24.
#define	receive	 25.
#define	socketa	 26.
#define	setreuid	 27.
#define	setregid	 28.
#define	gethstid	 31.
#define	sethstid	 32.
