.TH EM_DECODE 6 2017-01-18
.ad
.SH NAME
em_decode, em_encode \- compact to readable EM and v.v.
.SH SYNOPSIS
.B em_decode
[ inputfile [ outputfile ] ]
.br
.B em_encode
[ inputfile [ outputfile ] ]
.SH DESCRIPTION
Most programs involved with the EM project only produce and accept
EM programs in compact form.
These files are only machine readable.
A description of this compact form can be found in [1].
To inspect the code produced by compilers or to patch them for one reason
or another, human readable assembly code is needed.
em_decode produces human readable assembly code from the compact form.
.PP
em_decode accepts the normal compact form in both optimized and
unoptimized form.
.PP
em_encode produces the compact form
out of these human readable assembly code.
.PP
The first argument is the input file.
The second argument is the output file.
Both programs can act as a filter.
.SH "SEE ALSO"
.IP [1]
A.S.Tanenbaum, Ed Keizer, Hans van Staveren & J.W.Stevenson
"Description of a machine architecture for use of
block structured languages" Informatica rapport IR-81.
.IP [2]
ack(1)
.SH DIAGNOSTICS
Error messages are intended to be self-explanatory.
.SH AUTHOR
Ceriel Jacobs, Vrije Universiteit
