.TH ESIZE 1 2017-01-18
.SH NAME
esize \- print info from e.out header
.SH SYNOPSIS
.B esize
[ file ... ]
.SH DESCRIPTION
.I Esize
prints information from the
.I e.out
headers of the indicated files, including flags, word and pointer sizes,
text and data sizes, etc.
All values are in decimal.
.PP
If no parameters are given, the header of
.I e.out
is examined.
.SH SEE ALSO
The EM Manual, for the precise header information
.SH AUTHOR
Dick Grune
