CFLAGS=-L -LIB

.SUFFIXES: .o .e .c

.e.o:
	$(CC) $(CFLAGS) -c -o $@ $*.e

clean:
	rm -rf asin.o atan2.o atan.o ceil.o fabs.o pow.o log10.o \
		log.o sin.o sinh.o sqrt.o tan.o tanh.o exp.o ldexp.o \
		fmod.o floor.o frexp.o modf.o OLIST

asin.o:
atan2.o:
atan.o:
ceil.o:
fabs.o:
pow.o:
log10.o:
log.o:
sin.o:
sinh.o:
sqrt.o:
tan.o:
tanh.o:
exp.o:
ldexp.o:
fmod.o:
floor.o:
frexp.o:
modf.o:
