CFLAGS=-L -LIB -DNFS

.SUFFIXES: .o .e .c

.e.o:
	$(CC) $(CFLAGS) -c -o $@ $*.e

clean:
	rm -rf getgrent.o getopt.o getpass.o getpw.o getw.o putw.o \
		popen.o sleep.o termcap.o fdopen.o closedir.o getdents.o \
		opendir.o readdir.o rewinddir.o seekdir.o telldir.o OLIST

getgrent.o:
getopt.o:
getpass.o:
getpw.o:
getw.o:
putw.o:
popen.o:
sleep.o:
termcap.o:
fdopen.o:
closedir.o:
getdents.o:
opendir.o:
readdir.o:
rewinddir.o:
seekdir.o:
telldir.o:
