.SUFFIXES: .o .e .c

.e.o:
	$(CC) $(CFLAGS) -c -o $@ $*.e

clean:
	rm -rf tmpfile.o tmpnam.o rename.o remove.o fopen.o freopen.o \
		setbuf.o setvbuf.o perror.o fprintf.o printf.o sprintf.o \
		vfprintf.o vprintf.o vsprintf.o doprnt.o icompute.o \
		fscanf.o scanf.o sscanf.o doscan.o fgetc.o fgets.o getc.o \
		getchar.o gets.o putc.o putchar.o fputc.o puts.o fputs.o \
		ungetc.o fread.o fwrite.o fgetpos.o fsetpos.o rewind.o \
		fseek.o ftell.o clearerr.o feof.o ferror.o fileno.o \
		fltpr.o ecvt.o gcvt.o fillbuf.o fclose.o flushbuf.o \
		fflush.o isatty.o data.o OLIST

tmpfile.o:
tmpnam.o:
rename.o:
remove.o:
fopen.o:
freopen.o:
setbuf.o:
setvbuf.o:
perror.o:
fprintf.o:
printf.o:
sprintf.o:
vfprintf.o:
vprintf.o:
vsprintf.o:
doprnt.o:
icompute.o:
fscanf.o:
scanf.o:
sscanf.o:
doscan.o:
fgetc.o:
fgets.o:
getc.o:
getchar.o:
gets.o:
putc.o:
putchar.o:
fputc.o:
puts.o:
fputs.o:
ungetc.o:
fread.o:
fwrite.o:
fgetpos.o:
fsetpos.o:
rewind.o:
fseek.o:
ftell.o:
clearerr.o:
feof.o:
ferror.o:
fileno.o:
fltpr.o:
ecvt.o:
gcvt.o:
fillbuf.o:
fclose.o:
flushbuf.o:
fflush.o:
isatty.o:
data.o:
