#!/bin/sh
: '$Id$'

grep '^#' $3 >tokendefs
$1 -s $2 > $4 <<'!Funky!Stuff!'
g/^#/d
1,$s/\([^ 	]*\)[ 	][ 	]*\(.*\)/	sy_p=lookup("\1",symkeyw,newsymbol);sy_p->sy_value.syv_keywno=\2;/
1i
#include "lookup.h"
.
.r tokendefs
a

void enterkeyw(void) {
	register symbol *sy_p;

.
$a
}
.
1,$p
!Funky!Stuff!
rm tokendefs

