CFLAGS=-L -LIB

.SUFFIXES: .o .e .c

.e.o:
	$(CC) $(CFLAGS) -c -o $@ $*.e

clean:
	rm -rf ctime.o asctime.o localtime.o clock.o difftime.o gmtime.o \
		mktime.o strftime.o time.o tzset.o misc.o OLIST

ctime.o:
asctime.o:
localtime.o:
clock.o:
difftime.o:
gmtime.o:
mktime.o:
strftime.o:
time.o:
tzset.o:
misc.o:
