$cc $cflags bhcst.c
$cc $cflags bhdlb.c
$cc $cflags bhdnam.c
$cc $cflags bhfcon.c
$cc $cflags bhicon.c
$cc $cflags bhilb.c
$cc $cflags bhpnam.c
$cc $cflags bhucon.c
$cc $cflags crcst.c
$cc $cflags crdlb.c
$cc $cflags crdnam.c
$cc $cflags crfcon.c
$cc $cflags cricon.c
$cc $cflags crilb.c
$cc $cflags crpnam.c
$cc $cflags crscon.c
$cc $cflags crucon.c
$cc $cflags cst.c
$cc $cflags dfdlb.c
$cc $cflags dfdnam.c
$cc $cflags dfilb.c
$cc $cflags dlb.c
$cc $cflags dnam.c
$cc $cflags end.c
$cc $cflags endarg.c
$cc $cflags exc.c
$cc $cflags fcon.c
$cc $cflags icon.c
$cc $cflags ilb.c
$cc $cflags msend.c
$cc $cflags op.c
$cc $cflags opcst.c
$cc $cflags opdlb.c
$cc $cflags opdnam.c
$cc $cflags opilb.c
$cc $cflags opnarg.c
$cc $cflags oppnam.c
$cc $cflags pnam.c
$cc $cflags pro.c
$cc $cflags pronarg.c
$cc $cflags msstart.c
$cc $cflags psdlb.c
$cc $cflags psdnam.c
$cc $cflags pspnam.c
$cc $cflags scon.c
$cc $cflags ucon.c
$cc $cflags C_out.c

$cc $cflags $1/em.c
mv em.o em$1.o
$ar rc libem$1.a bhcst.o bhdlb.o bhdnam.o bhfcon.o bhicon.o bhilb.o bhpnam.o bhucon.o crcst.o crdlb.o crdnam.o crfcon.o cricon.o crilb.o crpnam.o crscon.o crucon.o cst.o dfdlb.o dfdnam.o dfilb.o dlb.o dnam.o end.o endarg.o exc.o failed.o fcon.o getid.o icon.o ilb.o insert.o internerr.o msend.o op.o opcst.o opdlb.o opdnam.o opilb.o opnarg.o oppnam.o pnam.o pro.o pronarg.o msstart.o psdlb.o psdnam.o pspnam.o scon.o ucon.o C_out.o em$1.o
