#!/bin/sh

while :
do
	echo $E_FLAG "Which system-call library do you want to install for the VAX?
You can choose between
	libbsd4_1a	for Berkeley Unix 4.1
	libbsd4_2	for Berkeley Unix 4.2 or newer, or Ultrix
	libsysV_2	for Unix System V
Your choice: [$SYSVAX] $E_SFX"
	. $FDIR/get_answer
	case $ANS in
	'')	ANS="$SYSVAX";;
	esac
	SYSVAX="$ANS"
	case $SYSVAX in
	libbsd4_1a|libbsd4_2|libsysV_2)
		break
		;;
	*)	echo "I do not understand your answer ($SYSVAX). Try again"
		;;
	esac
done
