#!/bin/sh
# compiler set for target machine

CC=cc#				# compiler to be used for compiling ACK

# always passed to $(CC) -c.
COPTIONS=-O -D_EM_WSIZE=4 -D_EM_PSIZE=4

# passed to $(CC) -c when compiling modules.
LIBOPTIONS=#
# LIBOPTIONS=-LIB -L		# when $(CC) is ACK

CC_AND_MKDEP=cc-and-mkdep.all#	# when $(CC) is neither ACK or SUN,
# CC_AND_MKDEP=cc-and-mkdep.ack## when $(CC) is an ACK-derived C compiler,
# CC_AND_MKDEP=cc-and-mkdep.sun## when $(CC) is a SUN C compiler

LDOPTIONS=#			# always passed to $(CC) when linking

SUF=o#				# suffix of files produced with $(CC) -c

AR=ar#				# archiver for Unix format objects
# AR=aal#			# archiver for ACK .o format objects
# AR=arch#			# archiver for ACK .s format objects

RANLIB=ranlib#			# when ranlib required
# RANLIB=:# 			# when ranlib not required

LIBSUF=a#			# suffix of object libraries
