for _, plat in ipairs(vars.plats) do
	acklibrary {
		name = "lib_"..plat,
		srcs = {
			"./adi.s",
			"./and.s",
			"./blm.s",
			"./cii.s",
			"./cms.s",
			"./com.s",
			"./csa4.s",
			"./csa8.s",
			"./csb4.s",
			"./csb8.s",
			"./cuu.s",
			"./divrem8.s",
			"./dup.s",
			"./dvi8.s",
			"./dvi.s",
			"./dvu8.s",
			"./dvu.s",
			"./error.s",
			"./exg.s",
			"./fat.s",
			"./fp8087.s",
			"./gto.s",
			"./iaar.s",
			"./ilar.s",
			"./inn.s",
			"./ior.s",
			"./isar.s",
			"./lar4.s",
			"./loi.s",
			"./mli8.s",
			"./mli.s",
			"./mon.s",
			"./ngi.s",
			"./nop.s",
			"./print.s",
			"./rck.s",
			"./rmi8.s",
			"./rmi.s",
			"./rmu.s",
			"./rol.s",
			"./ror.s",
			"./sar4.s",
			"./sbi.s",
			"./set.s",
			"./sli.s",
			"./sri.s",
			"./sti.s",
			"./strhp.s",
			"./trp.s",
			"./unknown.s",
			"./xor.s",
		},
		vars = { plat = plat },
	}
end

